const $=s=>document.querySelector(s),app=$("#app");
const eur=n=>n.toFixed(2).replace(".",",")+" €";
const ls={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}};
let cart=ls.get("noor-cart",[]);
function kami(c,w){const d=c.replace("#","");const L=parseInt(d,16),lum=((L>>16)*.3+((L>>8)&255)*.59+(L&255)*.11)>150;const s=lum?"rgba(0,0,0,.18)":"rgba(255,255,255,.14)";
return `<svg viewBox="0 0 200 300" role="img" aria-label="${w||'Kamis'}"><path d="M72 18l28 12 28-12 38 30 14 110-22 6-6-62-4 148H52l-4-148-6 62-22-6 14-110z" fill="${c}"/><path d="M100 30v120" stroke="${s}" stroke-width="1.5"/><path d="M72 18l28 12 28-12" fill="none" stroke="${s}" stroke-width="3"/><path d="M100 150v140M52 290h96" stroke="${s}" stroke-width="1" opacity=".5"/><circle cx="100" cy="52" r="1.8" fill="${s}"/><circle cx="100" cy="78" r="1.8" fill="${s}"/><circle cx="100" cy="104" r="1.8" fill="${s}"/></svg>`}
const star=`<svg class="pat" viewBox="0 0 200 200" fill="none" stroke="#D8C7AA" stroke-width=".5" aria-hidden="true"><g id="s"><rect x="50" y="50" width="100" height="100"/><rect x="50" y="50" width="100" height="100" transform="rotate(45 100 100)"/></g><use href="#s" transform="rotate(22.5 100 100) scale(.8) translate(25 25)"/><circle cx="100" cy="100" r="92"/><circle cx="100" cy="100" r="60"/></svg>`;
const save=()=>{ls.set("noor-cart",cart);const n=cart.reduce((a,i)=>a+i.q,0);$("#cnt").textContent=n;$("#cnt").style.display=n?"grid":"none"};
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("s");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("s"),2000)}
function add(id,size,color,q){const p=P.find(x=>x.id===id);const k=cart.find(i=>i.id===id&&i.size===size&&i.color===color);const have=k?k.q:0;if(have+q>p.stock){toast("Stock insuffisant");return false}
k?k.q+=q:cart.push({id,size,color,q});save();toast("Ajouté au panier");return true}
const prod=id=>P.find(p=>p.id===id);
function card(p){const b=p.stock<1?"ÉPUISÉ":(p.badge||"");return `<article class="card"><a href="#/produit/${p.id}" aria-label="${p.name}"><div class="ph">${b?`<span class="bd${b==="ÉPUISÉ"?" x":""}">${b}</span>`:""}${kami(p.colors[0][1],p.name+" — "+p.colors[0][0])}</div><h3>${p.name}</h3></a><div class="meta">${p.colors.map(c=>c[0]).join(", ")} · ${p.stock<1?"Indisponible":p.stock<6?"Plus que "+p.stock+" en stock":"En stock"}</div><div class="pr">${eur(p.price)}</div><button class="btn o" data-add="${p.id}" ${p.stock<1?"disabled":""}>Ajouter au panier</button></article>`}
function home(){const f=P.filter(p=>p.stock>0).slice(0,4);return `<section class="hero">${star}<div class="wrap"><div><h1>L'ÉLÉGANCE<br>DANS LA<br>SIMPLICITÉ</h1><p>Découvrez notre sélection de kamis conçus pour allier tradition, confort et élégance.</p><div class="row"><a class="btn" href="#/boutique">Découvrir la collection</a><a class="btn o" href="#/boutique?cat=nouveau">Voir les nouveautés</a></div></div><div class="fig">${kami("#CDB997","Kamis beige sable NOOR")}</div></div></section>
<section class="sec alt"><div class="wrap"><h2 class="t">NOS COLLECTIONS</h2><div class="cols">${[["KAMIS CLASSIQUES","Kamis sobres et intemporels.","#1d1d1d","classique"],["KAMIS PREMIUM","Matières et finitions plus raffinées.","#F1EEE6","premium"],["NOUVEAUTÉS","Découvrez les derniers modèles disponibles.","#CDB997","nouveau"]].map(c=>`<a class="col" href="#/boutique?cat=${c[3]}"><svg class="k" viewBox="0 0 200 300" style="width:auto" aria-hidden="true">${kami(c[2]).replace(/<svg[^>]*>|<\/svg>/g,"")}</svg><div style="background:linear-gradient(transparent,rgba(24,24,24,.95) 40%);margin:-28px;padding:60px 28px 28px;width:calc(100% + 56px)"><h3>${c[0]}</h3><p>${c[1]}</p><span class="btn o" style="padding:10px 20px">Découvrir</span></div></a>`).join("")}</div></div></section>
<section class="sec"><div class="wrap"><h2 class="t">NOS KAMIS</h2><div class="grid">${f.map(card).join("")}</div><p style="text-align:center;margin-top:48px"><a class="btn o" href="#/boutique">Voir toute la boutique</a></p></div></section>`}
function shop(qs){const u=new URLSearchParams(qs),S=window.fs=window.fs||{};if(u.has("cat"))S.cat=u.get("cat");if(u.has("q"))S.q=u.get("q");
const sizes=[...new Set(P.flatMap(p=>p.sizes))],cols=[...new Set(P.flatMap(p=>p.colors.map(c=>c[0])))];
return `<div class="wrap"><div class="top"><h1>Boutique</h1></div><div class="shop"><aside class="fil" aria-label="Filtres">
<div><label for="fc">Collection</label><select id="fc" data-f="cat"><option value="">Toutes</option><option value="classique">Classiques</option><option value="premium">Premium</option><option value="nouveau">Nouveautés</option></select></div>
<div><label for="fs">Taille</label><select id="fs" data-f="size"><option value="">Toutes</option>${sizes.map(s=>`<option>${s}</option>`).join("")}</select></div>
<div><label for="fo">Couleur</label><select id="fo" data-f="color"><option value="">Toutes</option>${cols.map(s=>`<option>${s}</option>`).join("")}</select></div>
<div><label for="fp">Prix</label><select id="fp" data-f="price"><option value="">Tous</option><option value="45">Jusqu'à 45 €</option><option value="50">Jusqu'à 50 €</option><option value="99">Plus de 50 €</option></select></div>
<div><label for="fd">Disponibilité</label><select id="fd" data-f="av"><option value="">Tous</option><option value="1">En stock</option></select></div></aside>
<div><div class="tools"><span id="n"></span><select id="so" data-f="sort" aria-label="Trier"><option value="new">Nouveautés</option><option value="asc">Prix croissant</option><option value="desc">Prix décroissant</option><option value="pop">Popularité</option></select></div><div class="grid" id="res" style="grid-template-columns:repeat(3,1fr)"></div></div></div></div>`}
function filt(){const S=window.fs||{};["cat","size","color","price","av","sort"].forEach(k=>{const e=document.querySelector(`[data-f=${k}]`);if(e&&S[k]!=null)e.value=S[k]});
let r=P.filter(p=>(!S.cat||(S.cat==="nouveau"?p.isNew:S.cat==="kamis"||p.cat===S.cat))&&(!S.size||p.sizes.includes(S.size))&&(!S.color||p.colors.some(c=>c[0]===S.color))&&(!S.av||p.stock>0)&&(!S.price||(S.price==="99"?p.price>50:p.price<=+S.price))&&(!S.q||(p.name+p.desc).toLowerCase().includes(S.q.toLowerCase())));
const o=S.sort||"new";r.sort((a,b)=>o==="asc"?a.price-b.price:o==="desc"?b.price-a.price:o==="pop"?b.pop-a.pop:b.date-a.date);
$("#n").textContent=r.length+" produit"+(r.length>1?"s":"");$("#res").innerHTML=r.map(card).join("")||"<p>Aucun produit ne correspond. Modifiez vos filtres.</p>"}
let sel={};
function product(id){const p=prod(id);if(!p)return `<div class="ok"><h1>Produit introuvable</h1><a class="btn" href="#/boutique">Retour à la boutique</a></div>`;sel={id,size:"",ci:0,q:1};
const rel=P.filter(x=>x.id!==id).sort((a,b)=>(b.cat===p.cat)-(a.cat===p.cat)).slice(0,4);
return `<div class="wrap"><div class="pd"><div class="gal"><div class="th" id="th"></div><div class="main" id="mn"></div></div><div>
<h1>${p.name}</h1><div class="pr" style="font-size:22px;margin:6px 0">${eur(p.price)}</div><div class="meta" style="color:var(--muted);font-size:14px">Réf. ${p.ref} · ${p.stock<1?"Épuisé":"En stock"}</div>
<p style="color:var(--muted)">${p.desc}</p>
<div class="fld"><b>Couleur : <span id="cn">${p.colors[0][0]}</span></b><div class="chips">${p.colors.map((c,i)=>`<button class="sw${i?"":" on"}" data-c="${i}" style="background:${c[1]}" aria-label="${c[0]}"></button>`).join("")}</div></div>
<div class="fld"><b>Taille</b><div class="chips" role="group" aria-label="Taille">${p.sizes.map(s=>`<button class="chip" data-s="${s}" ${p.stock<1?"disabled":""}>${s}</button>`).join("")}</div></div>
<div class="fld"><b>Quantité</b><div class="qty"><button data-qd aria-label="Moins">−</button><span id="qv">1</span><button data-qu aria-label="Plus">+</button></div></div>
<button class="btn" style="width:100%" id="addp" ${p.stock<1?"disabled":""}>${p.stock<1?"Épuisé":"AJOUTER AU PANIER"}</button>
<div style="margin-top:28px"><details open><summary>Description</summary><p>${p.desc} Une pièce simple et durable, pensée pour s'adapter à votre quotidien.</p></details>
<details><summary>Détails</summary><ul><li>Matière : ${p.mat}</li><li>Coupe : droite, longueur mi-mollet</li><li>Entretien : lavage 30 °C, repassage doux</li><li>Tailles disponibles : ${p.sizes.join(", ")}</li></ul></details>
<details><summary>Livraison</summary><p>${SHIPPING.text}</p></details><details><summary>Retours</summary><p>${RETURNS}</p></details></div></div></div></div>
<section class="sec alt"><div class="wrap"><h2 class="t">VOUS AIMEREZ AUSSI</h2><div class="grid">${rel.map(card).join("")}</div></div></section>`}
function gal(){const p=prod(sel.id),c=p.colors[sel.ci];$("#mn").innerHTML=kami(c[1],p.name+" — "+c[0]);$("#th").innerHTML=[0,1,2].map(i=>`<button class="${i?"":"on"}" aria-label="Vue ${i+1}">${kami(c[1])}</button>`).join("");$("#cn").textContent=c[0]}
const totals=()=>{const sub=cart.reduce((a,i)=>a+prod(i.id).price*i.q,0);const sh=!cart.length||sub>=SHIPPING.free?0:SHIPPING.fee;return{sub,sh,tot:sub+sh}};
function cartV(){if(!cart.length)return `<div class="ok"><h1>Votre panier est vide</h1><p style="color:var(--muted)">Parcourez la collection pour trouver votre kamis.</p><a class="btn" href="#/boutique">Découvrir la boutique</a></div>`;const t=totals();
return `<div class="wrap"><div class="top"><h1>Panier</h1></div><div class="ct"><div>${cart.map((i,n)=>{const p=prod(i.id),c=p.colors.find(c=>c[0]===i.color)||p.colors[0];return `<div class="li"><div class="ph">${kami(c[1],p.name)}</div><div><h3 style="font-size:20px">${p.name}</h3><div class="meta" style="color:var(--muted);font-size:14px">Taille ${i.size} · ${i.color}</div><div class="qty" style="margin-top:8px"><button data-ci="${n}" data-d="-1" aria-label="Moins">−</button><span>${i.q}</span><button data-ci="${n}" data-d="1" aria-label="Plus">+</button></div></div><div style="text-align:right"><div class="pr">${eur(p.price*i.q)}</div><button class="ib" style="width:auto;font-size:13px;color:var(--muted)" data-rm="${n}">Supprimer</button></div></div>`}).join("")}</div>
${sumV(t)}<a class="btn" style="width:100%;text-align:center;margin-top:18px;display:block;grid-column:2" href="#/commande">PASSER LA COMMANDE</a>
</div></div>`}
function sumV(t){return `<div class="sum"><h3 style="margin-bottom:12px">Résumé</h3><div class="r"><span>Sous-total</span><span>${eur(t.sub)}</span></div><div class="r"><span>Livraison</span><span>${t.sh?eur(t.sh):"Offerte"}</span></div><div class="r tt"><span>Total</span><span>${eur(t.tot)}</span></div></div>`}
function checkout(){if(!cart.length)return cartV();const t=totals();
return `<div class="wrap"><div class="top"><h1>Commande</h1></div><form class="ct" id="ck"><div><div class="f2"><div><label for="a1">Prénom</label><input id="a1" required autocomplete="given-name"></div><div><label for="a2">Nom</label><input id="a2" required autocomplete="family-name"></div><div><label for="a3">Email</label><input id="a3" type="email" required autocomplete="email"></div><div><label for="a4">Téléphone</label><input id="a4" type="tel" required autocomplete="tel"></div><div class="full"><label for="a5">Adresse</label><input id="a5" required autocomplete="street-address"></div><div><label for="a6">Ville</label><input id="a6" required></div><div><label for="a7">Code postal</label><input id="a7" required autocomplete="postal-code"></div><div class="full"><label for="a8">Pays</label><select id="a8"><option>France</option><option>Belgique</option><option>Suisse</option><option>Luxembourg</option></select></div></div>
<h3 style="margin:32px 0 12px">Livraison</h3><label style="display:flex;gap:12px;align-items:center;border:1px solid var(--sand);padding:16px;color:var(--ivory)"><input type="radio" checked style="width:18px;min-height:0"> Livraison suivie · 3 à 5 jours · ${t.sh?eur(t.sh):"Offerte"}</label>
<h3 style="margin:32px 0 12px">Paiement sécurisé</h3><p style="color:var(--muted);font-size:14px">Emplacement réservé : connectez ici votre prestataire (Stripe, PayPal…). Dans cette version, la commande est simulée et aucun paiement n'est débité.</p></div>
<div>${sumV(t)}<button class="btn" style="width:100%;margin-top:18px" type="submit">CONFIRMER LA COMMANDE</button><div class="rs"><span>🔒 Paiement sécurisé</span><span>📦 Livraison suivie</span><span>↩️ Retours possibles selon les conditions</span></div></div></form></div>`}
const about=()=>`<div class="wrap sec"><h1 style="font-size:clamp(36px,5vw,56px);margin-bottom:32px">À propos</h1><p class="big">NOOR est une boutique spécialisée dans les vêtements traditionnels musulmans, pensée autour d'une idée simple : proposer des vêtements élégants, confortables et intemporels.</p><div class="prose" style="margin-top:32px"><p>Notre identité repose sur l'équilibre entre tradition et modernité : des coupes sobres, des matières choisies et des finitions soignées, pour un vêtement qui se porte avec naturel au quotidien.</p><p>Chaque modèle est conçu pour durer, sans artifice.</p></div><p style="margin-top:32px"><a class="btn" href="#/boutique">Découvrir la collection</a></p></div>`;
const contact=()=>`<div class="wrap"><div class="top"><h1>Contact</h1></div><div class="ct" style="grid-template-columns:1.3fr 1fr"><form id="cf" class="f2"><div><label for="c1">Prénom</label><input id="c1" required></div><div><label for="c2">Nom</label><input id="c2" required></div><div class="full"><label for="c3">Email</label><input id="c3" type="email" required></div><div class="full"><label for="c4">Sujet</label><input id="c4" required></div><div class="full"><label for="c5">Message</label><textarea id="c5" rows="6" required></textarea></div><div class="full"><button class="btn" type="submit">ENVOYER LE MESSAGE</button></div></form>
<div class="sum"><h3>Nous joindre</h3><p style="color:var(--muted)">Email : contact@votre-domaine.fr<br>Instagram : @votre_compte<br>TikTok : @votre_compte<br>Facebook : /votre-page</p><p style="color:var(--muted)">Réponse sous 24 à 48 h, du lundi au vendredi.</p></div></div></div>`;
function route(){const h=location.hash.slice(1)||"/",[path,qs]=h.split("?"),seg=path.split("/");let v;
if(seg[1]==="boutique"){if(!qs)window.fs={};v=shop(qs)}else v=seg[1]==="produit"?product(seg[2]):seg[1]==="panier"?cartV():seg[1]==="commande"?checkout():seg[1]==="a-propos"?about():seg[1]==="contact"?contact():home();
app.innerHTML=v;if(seg[1]==="boutique")filt();if(seg[1]==="produit"&&prod(seg[2]))gal();
document.querySelectorAll("nav.m a").forEach(a=>a.classList.toggle("on",a.getAttribute("href")==="#"+h));$("#nav").classList.remove("open");$("#burger").setAttribute("aria-expanded","false");window.scrollTo(0,0);
document.title=seg[1]==="produit"&&prod(seg[2])?prod(seg[2]).name+" — NOOR":"NOOR — Kamis et vêtements traditionnels musulmans"}
document.addEventListener("click",e=>{const t=e.target.closest("button");if(!t)return;
if(t.dataset.add){const p=prod(t.dataset.add);if(p.sizes.length>1){location.hash="#/produit/"+p.id;toast("Choisissez une taille")}else add(p.id,p.sizes[0],p.colors[0][0],1)}
else if(t.dataset.s){sel.size=t.dataset.s;document.querySelectorAll("[data-s]").forEach(b=>b.classList.toggle("on",b===t))}
else if(t.dataset.c!=null){sel.ci=+t.dataset.c;document.querySelectorAll("[data-c]").forEach(b=>b.classList.toggle("on",b===t));gal()}
else if(t.hasAttribute("data-qd")||t.hasAttribute("data-qu")){sel.q=Math.max(1,sel.q+(t.hasAttribute("data-qu")?1:-1));$("#qv").textContent=sel.q}
else if(t.id==="addp"){if(!sel.size){toast("Choisissez une taille");return}add(sel.id,sel.size,prod(sel.id).colors[sel.ci][0],sel.q)}
else if(t.dataset.d){const i=cart[+t.dataset.ci],p=prod(i.id),q=i.q+ +t.dataset.d;if(q<1)return;if(q>p.stock){toast("Stock insuffisant");return}i.q=q;save();route()}
else if(t.dataset.rm){cart.splice(+t.dataset.rm,1);save();route()}
else if(t.id==="sbtn"){$("#sbar").classList.toggle("open");$("#q").focus()}
else if(t.id==="burger"){const o=$("#nav").classList.toggle("open");t.setAttribute("aria-expanded",o)}});
document.addEventListener("change",e=>{const f=e.target.dataset.f;if(f){(window.fs=window.fs||{})[f]=e.target.value;filt()}});
document.addEventListener("submit",e=>{e.preventDefault();if(e.target.id==="ck"){const n="NR-"+Date.now().toString().slice(-6);cart=[];save();app.innerHTML=`<div class="ok wrap"><h1>Merci pour votre commande</h1><p style="color:var(--muted)">Commande n° ${n}. Un email de confirmation vous sera envoyé.</p><a class="btn" href="#/boutique">Continuer vos achats</a></div>`;scrollTo(0,0)}
else if(e.target.id==="cf"){e.target.outerHTML=`<div class="sum"><h3>Message envoyé</h3><p style="color:var(--muted)">Merci, nous vous répondons rapidement.</p></div>`}});
$("#q").addEventListener("keydown",e=>{if(e.key==="Enter"){window.fs={q:e.target.value};location.hash="#/boutique?q="+encodeURIComponent(e.target.value);route()}});
addEventListener("hashchange",route);save();route();
