/* ===== CATALOGUE : modifiez ou ajoutez des produits ici ===== */
const SHIPPING={free:80,fee:4.9,text:"Livraison suivie 3 à 5 jours ouvrés. 4,90 € — offerte dès 80 € d'achat."};
const RETURNS="Retours acceptés sous 14 jours après réception, article non porté et dans son emballage d'origine.";
const P=[
{id:"noir-classique",ref:"NR-001",name:"Kamis Noir Classique",price:39.9,cat:"classique",isNew:false,badge:"BEST-SELLER",pop:95,date:3,stock:24,colors:[["Noir","#1d1d1d"]],sizes:["S","M","L","XL","XXL"],mat:"Coton-polyester doux, opaque",desc:"Un kamis noir sobre à la coupe droite, pensé pour le quotidien comme pour les jours de prière. Col mao discret, patte de boutonnage cousue main."},
{id:"beige-sable",ref:"NR-002",name:"Kamis Beige Sable",price:44.9,cat:"classique",isNew:true,badge:"NOUVEAU",pop:80,date:9,stock:15,colors:[["Beige sable","#CDB997"],["Blanc cassé","#E9E3D3"]],sizes:["S","M","L","XL"],mat:"Coton léger et respirant",desc:"Une teinte sable lumineuse, chaude sans être voyante. Tombé fluide et finitions soignées pour un confort durable."},
{id:"blanc-premium",ref:"NR-003",name:"Kamis Blanc Premium",price:49.9,cat:"premium",isNew:false,badge:"",pop:90,date:5,stock:12,colors:[["Blanc","#F1EEE6"]],sizes:["M","L","XL","XXL"],mat:"Coton premium 100 %, tissage serré",desc:"Notre blanc le plus raffiné : matière dense et opaque, broderie tonale discrète au col, coupe élégante."},
{id:"marron-sable",ref:"NR-004",name:"Kamis Marron Sable",price:44.9,cat:"classique",isNew:true,badge:"NOUVEAU",pop:70,date:10,stock:9,colors:[["Marron","#6B5640"]],sizes:["S","M","L"],mat:"Coton-viscose, toucher souple",desc:"Un marron terreux et profond, facile à porter. Fluide, léger, avec un col boutonné discret."},
{id:"anthracite-premium",ref:"NR-005",name:"Kamis Anthracite Premium",price:54.9,cat:"premium",isNew:false,badge:"BEST-SELLER",pop:85,date:4,stock:7,colors:[["Anthracite","#3a3a3c"],["Noir","#1d1d1d"]],sizes:["M","L","XL"],mat:"Mélange coton-lin",desc:"Un anthracite sobre avec une subtile texture lin. Finitions premium, passepoils discrets et grand confort."},
{id:"creme-premium",ref:"NR-006",name:"Kamis Crème Premium",price:52.9,cat:"premium",isNew:true,badge:"NOUVEAU",pop:75,date:11,stock:11,colors:[["Crème","#E8DDCA"]],sizes:["S","M","L","XL"],mat:"Coton peigné, finition satinée",desc:"Un crème doux et lumineux, au tombé impeccable. Pensé pour les occasions où l'on veut être simplement élégant."},
{id:"gris-classique",ref:"NR-007",name:"Kamis Gris Pierre",price:39.9,cat:"classique",isNew:false,badge:"",pop:60,date:2,stock:18,colors:[["Gris pierre","#8c8a84"]],sizes:["S","M","L","XL","XXL"],mat:"Coton-polyester",desc:"Un gris pierre neutre et intemporel, simple à entretenir, idéal au quotidien."},
{id:"olive-premium",ref:"NR-008",name:"Kamis Olive Premium",price:49.9,cat:"premium",isNew:false,badge:"ÉPUISÉ",pop:55,date:1,stock:0,colors:[["Olive","#5b5a3e"]],sizes:["M","L","XL"],mat:"Coton premium",desc:"Un vert olive profond et discret. Actuellement épuisé — retour en stock prochainement."}
];
